name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

permissions:
  contents: "read"
  packages: "write"

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: ubuntu-latest
    steps:
      - name: "setup"
        id: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-python-env@trunk"
      - name: "install deps"
        run: "poetry install"
      - name: "setup / login to ghcr"
        if: "${{ github.event_name == 'push' && steps.setup.outputs.publishing_branch != ''}}"
        uses: "docker/login-action@v3.3.0"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "docker / build"
        run: "docker build -t ghcr.io/kyoripowered/pydisgit ."
      - name: "docker / push"
        if: "${{ github.event_name == 'push' && steps.setup.outputs.publishing_branch != ''}}"
        run: "docker push ghcr.io/kyoripowered/pydisgit"


